// Generated by Apple Swift version 4.2 effective-3.4 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
#endif

#import <AWSDK/AWSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AWSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;
@class UIImage;

SWIFT_CLASS("_TtC5AWSDK10AWBranding")
@interface AWBranding : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AWBranding * _Nonnull sharedBranding;)
+ (AWBranding * _Nonnull)sharedBranding SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
/// @return Retrieve from the payload the organization name set in console. nil will be returned if nothing was present
- (NSString * _Nullable)organizationName SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)toolbarColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)toolbarTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)primaryColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)secondaryColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)primaryTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)secondaryTextColor SWIFT_WARN_UNUSED_RESULT;
/// @brief Attempt to retrieve the background image set by console or plist entry, or nil if not set.
/// @description If console branding is enabled then the downloaded image from console will be returned if it was set and downloaded.
/// If the file could not be downloaded or was not set, then attempt to retrieve an image from the plist entry set in AWSDKDefaultSettings.
/// If the image does not exist or was not set, nil is returned. The appropriate image will be returned based on device currently being used.
- (UIImage * _Nullable)primaryImage SWIFT_WARN_UNUSED_RESULT;
/// @brief Attempt to retrieve the company logo image set by console or plist entry or the default VMWare logo.
/// @description If console branding is enabled then the downloaded image from console will be returned if it was set and downloaded.
/// If the file could not be downloaded or was not set, then attempt to retrieve an image from the plist entry set in AWSDKDefaultSettings.
/// If the image does not exist or was not set, nil is returned. The appropriate image will be returned based on device currently being used.
- (UIImage * _Nullable)secondaryImage SWIFT_WARN_UNUSED_RESULT;
@end

@protocol AWSDKDelegate;
@protocol AWControllerCommandManagementDelegate;

SWIFT_CLASS("_TtC5AWSDK12AWController")
@interface AWController : NSObject
/// Returns current AirWatch SDK Version.
@property (nonatomic, readonly, copy) NSString * _Nonnull AWSDKVersion;
+ (AWController * _Nonnull)clientInstance SWIFT_WARN_UNUSED_RESULT;
/// Delegate to receive events such as received profiles, locked, initialCheckDone etc.
/// note:
///
/// Since AWController is a singleton, setting this delegate will reset previously set delegate.
/// <ul>
///   <li>
///   </li>
/// </ul>
@property (nonatomic, weak) id <AWSDKDelegate> _Nullable delegate;
/// Delegate to receieve events regarding command processor.
/// If your application supports commands delivered by the console, you can listen to events such
/// as started loading commands, failed and finished loading commands.
/// note:
///
/// Since AWController is a singleton, setting this delegate will reset previously set command management delegate.
/// <ul>
///   <li>
///   </li>
/// </ul>
@property (nonatomic, weak) id <AWControllerCommandManagementDelegate> _Nullable commandManagementDelegate;
/// Callback scheme for the application to be used to flip to Anchor Applications and back from it.
@property (nonatomic, copy) NSString * _Nonnull callbackScheme;
/// APNS Token to pass to console for push notifications regarding profiles, etc.
@property (nonatomic, copy) NSString * _Nonnull APNSToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)start;
- (void)sync;
- (void)refreshSDK;
- (BOOL)handleOpenURL:(NSURL * _Nullable)url fromApplication:(NSString * _Nullable)fromApplication SWIFT_WARN_UNUSED_RESULT;
@end


@interface AWController (SWIFT_EXTENSION(AWSDK))
/// This function is used to unwrap data passed in as the sole parameter with the Application Key generated from the successful initialization of AWSDK
/// \param data The data of type <code>Data</code> that is to be unwrapped
///
///
/// throws:
/// If any error occurs during unwrapping, throws an instance of NSError that describes the problem.
/// The error codes are defined by enum AWSDKCryptError.
///
/// returns:
/// An instance of type <code>Data</code> will be returned which represents the unwrapped version of the passed-in data
- (NSData * _Nullable)unwrap:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// This function is used to wrap data passed in as the sole parameter with the Application Key generated from the successful initialization of AWSDK
/// \param data The data of type <code>Data</code> that is to be wrapped
///
///
/// throws:
/// If any error occurs during wrapping, throws an instance of NSError that describes the problem.
/// The error codes are defined by enum AWSDKCryptError.
///
/// returns:
/// An instance of type <code>Data</code> will be returned which represents the wrapped version of the passed-in data
- (NSData * _Nullable)wrap:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


@interface AWController (SWIFT_EXTENSION(AWSDK))
/// This function is used to decrypt data passed in as the sole parameter with the Application Key generated from the successful initialization of AWSDK
/// \param data The data of type <code>Data</code> that is to be decrypted
///
///
/// throws:
/// If any error occurs during decryption, throws an instance of NSError that describes the problem.
/// The error codes are defined by enum AWSDKCryptError.
///
/// returns:
/// An instance of type <code>Data</code> will be returned which represents the decrypted version of the passed-in data
- (NSData * _Nullable)decrypt:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// This function is used to encrypt data passed in as the sole parameter with the Application Key generated from the successful initialization of AWSDK
/// \param data The data of type <code>Data</code> that is to be encrypted
///
///
/// throws:
/// If any error occurs during encryption, throws an instance of NSError that describes the problem.
/// The error codes are defined by enum AWSDKCryptError.
///
/// returns:
/// An instance of type <code>Data</code> will be returned which represents the encrypted version of the passed-in data
- (NSData * _Nullable)encrypt:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

@protocol CommandHandler;

@interface AWController (SWIFT_EXTENSION(AWSDK))
- (void)loadCommands;
- (void)registerCommandHandler:(id <CommandHandler> _Nonnull)commandHandler;
@end

@class NSURLProtectionSpace;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;
@class NSError;

@interface AWController (SWIFT_EXTENSION(AWSDK))
- (BOOL)canHandleProtectionSpace:(NSURLProtectionSpace * _Nullable)protectionSpace withError:(NSError * _Nullable * _Nullable)error;
- (BOOL)handleChallengeForURLSession:(NSURLAuthenticationChallenge * _Nullable)challenge completionHandler:(void (^ _Nullable)(enum NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (void)clearAndRefetchClientCertificateCredentialsWithCompletionHandler:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completionHandler;
- (BOOL)setPendingCertificateRetryWithTimeout:(double)timeout maxAttempts:(NSInteger)maxAttempts SWIFT_WARN_UNUSED_RESULT;
@end

@class AWEnrollmentAccount;

@interface AWController (SWIFT_EXTENSION(AWSDK))
@property (nonatomic, readonly, strong) AWEnrollmentAccount * _Nullable account;
/// This method invokes a UI with username and password fields which updates the user account with the populated
/// values after authenticating successfully. If the call to this method is done before the <code>AWControllerDelegate</code> callback
/// method <code>controllerDidCompleteVerificationWithServer:</code>, the call will not be triggered immediately.
/// It will be queued and will be triggered once SDK is done with current running operations.
/// \param completion A block object to be executed when updating the user credentials is finished.
/// The Boolean value indicates whether the update succeed and error in case it failed.
///
- (void)updateUserCredentialsWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end

@class AWProfile;

@interface AWController (SWIFT_EXTENSION(AWSDK))
- (AWProfile * _Nullable)sdkProfile SWIFT_WARN_UNUSED_RESULT;
- (AWProfile * _Nullable)appProfile SWIFT_WARN_UNUSED_RESULT;
/// List of downloaded profiles from Server. This property will return a cached list of profiles. If you want to retrieve profiles please make sure you call
@property (nonatomic, readonly, copy) NSArray<AWProfile *> * _Nonnull profiles;
- (void)setProfilesToRequest:(NSArray<NSString *> * _Nonnull)profileTypes;
@end

enum AWSSOStatus : NSInteger;

@interface AWController (SWIFT_EXTENSION(AWSDK))
- (NSString * _Nullable)deviceServicesURL SWIFT_WARN_UNUSED_RESULT;
- (void)queryDeviceEnrollmentStatus:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
- (void)sendLogDataWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@property (nonatomic, readonly) enum AWSSOStatus ssoStatus;
@end

enum AWEnrollmentStatus : NSInteger;
enum AWNetworkActivityStatus : NSInteger;
enum AWUnenrolledReason : NSInteger;

SWIFT_PROTOCOL_NAMED("AWControllerDelegate")
@protocol AWSDKDelegate
- (void)initialCheckDoneWithError:(NSError * _Nullable)error;
@optional
- (void)completedVerificationWithServer:(BOOL)success error:(NSError * _Nullable)error;
- (void)receivedProfiles:(NSArray<AWProfile *> * _Nonnull)profiles;
- (void)didReceiveEnrollmentStatus:(enum AWEnrollmentStatus)enrollmentStatus;
- (void)userChanged;
- (void)wipe;
- (void)willLock;
- (void)lock;
- (void)unlock;
- (void)stopNetworkActivity:(enum AWNetworkActivityStatus)reason;
- (void)resumeNetworkActivity;
- (BOOL)shouldStartEnrollmentAfterUnenrolled:(enum AWUnenrolledReason)reason SWIFT_WARN_UNUSED_RESULT;
- (void)didStartServerTrustValidationOnHost:(NSString * _Nonnull)host request:(NSURLRequest * _Nullable)request;
- (void)didFailServerTrustValidationOnHost:(NSString * _Nonnull)host request:(NSURLRequest * _Nullable)request;
- (void)didCompletelServerTrustValidationOnHost:(NSString * _Nonnull)host request:(NSURLRequest * _Nullable)request allowingConnection:(BOOL)allowingConnection;
- (void)didFinishPollingForPendingCertificateIssued:(BOOL)certificateIssued error:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC5AWSDK5AWSDK")
@interface AWSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWEnrollmentStatus, "EnrollmentStatus", closed) {
  AWEnrollmentStatusDeviceNotFound = 0,
  AWEnrollmentStatusDiscovered = 1,
  AWEnrollmentStatusRegistered = 2,
  AWEnrollmentStatusEnrollmentInProgress = 3,
  AWEnrollmentStatusEnrolled = 4,
  AWEnrollmentStatusEnterpriseWipePending = 5,
  AWEnrollmentStatusDeviceWipePending = 6,
  AWEnrollmentStatusRetired = 7,
  AWEnrollmentStatusUnenrolled = 8,
  AWEnrollmentStatusUnknown = 9,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWComplianceStatus, "ComplianceStatus", closed) {
  AWComplianceStatusUnknown = 0,
  AWComplianceStatusAllowed = 1,
  AWComplianceStatusBlocked = 2,
  AWComplianceStatusCompliant = 3,
  AWComplianceStatusNonCompliant = 4,
  AWComplianceStatusNotAvailable = 5,
  AWComplianceStatusNotApplicable = 6,
  AWComplianceStatusPendingComplianceCheck = 7,
  AWComplianceStatusPendingComplianceCheckForAPolicy = 8,
  AWComplianceStatusRegistrationActive = 9,
  AWComplianceStatusRegistrationExpired = 10,
  AWComplianceStatusQuarantined = 11,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWDeviceManagmentType, "DeviceManagmentType", closed) {
  AWDeviceManagmentTypeNotManaged = 0,
  AWDeviceManagmentTypeManagedByMDM = 1,
  AWDeviceManagmentTypeManagedByMAM = 2,
  AWDeviceManagmentTypeQuarantine = 3,
  AWDeviceManagmentTypeApplication = 4,
  AWDeviceManagmentTypeWorkspaceOne = 5,
  AWDeviceManagmentTypeOffline = 6,
  AWDeviceManagmentTypeUnknown = 7,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWSSOStatus, "SSOStatus", closed) {
  AWSSOStatusUnknown = 0,
  AWSSOStatusEnabled = 1,
  AWSSOStatusDisabled = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWRequeryType, "RequeryType", closed) {
  AWRequeryApplist SWIFT_COMPILE_NAME("appList") = 1,
  AWRequeryDeviceInfo SWIFT_COMPILE_NAME("deviceInfo") = 2,
  AWRequeryProfileInfo SWIFT_COMPILE_NAME("profileInfo") = 3,
  AWRequerySecurityInfo SWIFT_COMPILE_NAME("securityInfo") = 4,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWNetworkActivityStatus, "NetworkActivityStatus", closed) {
/// Initial/unknown state
  AWNetworkActivityInit SWIFT_COMPILE_NAME("unknown") = 0,
/// Normal
  AWNetworkActivityNormal SWIFT_COMPILE_NAME("normal") = 1,
/// When Either there is no network (no wifi or cellular) or in airplane mode.
  AWNetworkActivityNetworkNotReachable SWIFT_COMPILE_NAME("networkNotReachable") = 2,
/// SSID does not match what is listed
  AWNetworkActivityBadSSID SWIFT_COMPILE_NAME("connectedToUnknownSSID") = 3,
/// Celluar data is completely disabled
  AWNetworkActivityCellularDisabled SWIFT_COMPILE_NAME("cellularDataConnectionDisabled") = 4,
/// Celluar data is disabled while roaming
  AWNetworkActivityRoaming SWIFT_COMPILE_NAME("cellularDataConnectionDisabledWhileRoaming") = 5,
/// Proxy setup failed.
  AWNetworkActivityProxyFailed SWIFT_COMPILE_NAME("proxySetupFailed") = 6,
/// offline access is not allowed or maximum offline time has reached
  AWNetworkOfflineNotAllowed SWIFT_COMPILE_NAME("offlineNotAllowed") = 7,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWAuthenticationMethod, "AuthenticationMethod", closed) {
  AWAuthenticationMethodNone = 0,
  AWAuthenticationMethodPasscode = 1,
  AWAuthenticationMethodUsernamePassword = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWBiometricMethod, "BiometricMethod", closed) {
  AWBiometricMethodNone = 0,
  AWBiometricMethodAny = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWPasscodeMode, "PasscodeMode", closed) {
  AWPasscodeModeOff = 0,
  AWPasscodeModeNumeric = 1,
  AWPasscodeModeAlphanumeric = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWProxyType, "ProxyType", closed) {
  AWProxyTypeNone = 0,
  AWProxyTypeMag = 1,
  AWProxyTypeStandard = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWUnenrolledReason, "UnenrollmentReason", closed) {
  AWUnenrolledReasonServerUnenrolled = 0,
  AWUnenrolledReasonUserFailedToAuthenticate = 1,
};


@interface AWSDK (SWIFT_EXTENSION(AWSDK))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWConfigurationProfileType, "ConfigurationProfileType", closed) {
  AWConfigurationProfileUnknown SWIFT_COMPILE_NAME("unknown") = 0,
  AWConfigurationProfileAgent SWIFT_COMPILE_NAME("agent") = 5,
  AWConfigurationProfileBrowser SWIFT_COMPILE_NAME("browser") = 7,
  AWConfigurationProfileContentLocker SWIFT_COMPILE_NAME("contentLocker") = 9,
  AWConfigurationProfileSharedDevice SWIFT_COMPILE_NAME("sharedDevice") = 13,
  AWConfigurationProfileSDKV2 SWIFT_COMPILE_NAME("sdk") = 21,
  AWConfigurationProfileSDKV2AppWrapping SWIFT_COMPILE_NAME("sdkAppWrapping") = 22,
  AWConfigurationProfileBoxer SWIFT_COMPILE_NAME("boxer") = 32,
};


@interface AWSDK (SWIFT_EXTENSION(AWSDK))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWWebsiteFilterType, "WebsiteFilterType", closed) {
  AWWebsiteFilterTypeUnknown = 0,
  AWWebsiteFilterTypeDeny = 1,
  AWWebsiteFilterTypeAllow = 2,
};


@interface AWSDK (SWIFT_EXTENSION(AWSDK))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWEnrollmentAuthenticationCredentials, "EnrollmentAuthenticationCredentialsType", closed) {
  AWEnrollmentAuthenticationCredentialsNone = 0,
  AWEnrollmentAuthenticationCredentialsPin = 1,
  AWEnrollmentAuthenticationCredentialsUsernamePassword = 2,
  AWEnrollmentAuthenticationCredentialsCertificate = 3,
  AWEnrollmentAuthenticationCredentialsCertificateWithPin = 4,
  AWEnrollmentAuthenticationCredentialsAuthorizationToken = 5,
  AWEnrollmentAuthenticationCredentialsSso = 6,
};


@interface AWSDK (SWIFT_EXTENSION(AWSDK))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWCommandType, "CommandType", closed) {
  AWCommandTypeInstallProfiles = 0,
  AWCommandTypeRequestProfiles = 1,
  AWCommandTypeUploadLogs = 2,
  AWCommandTypeLockSSO = 3,
  AWCommandTypeCustom = 4,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWCommandStatus, "CommandStatus", closed) {
  AWCommandStatusUnknown = 0,
  AWCommandStatusAcknowledged = 1,
  AWCommandStatusError = 2,
  AWCommandStatusCommandFormatError = 3,
  AWCommandStatusIdle = 4,
  AWCommandStatusNotNow = 5,
};


@interface AWSDK (SWIFT_EXTENSION(AWSDK))
@end

typedef SWIFT_ENUM_NAMED(uint16_t, AWAnalyticsEvent, "AnalyticsEvent", closed) {
  AWAnalyticsEventCustomEvent = 0,
  AWAnalyticsEventSessionStarted = 1,
  AWAnalyticsEventSessionEnded = 2,
  AWAnalyticsEventViewDidAppear = 3,
  AWAnalyticsEventViewDidDisappear = 4,
};

typedef SWIFT_ENUM_NAMED(uint16_t, AWAnalyticsEventValueType, "AnalyticsEventValueType", closed) {
  AWAnalyticsEventValueTypeNone = 0,
  AWAnalyticsEventValueTypeInteger = 1,
  AWAnalyticsEventValueTypeLong = 2,
  AWAnalyticsEventValueTypeString = 3,
};




@interface AWSDK (SWIFT_EXTENSION(AWSDK))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWNetworkAccessAllowCellular, "AllowCellularNetworkAccess", closed) {
  AWNetworkAccessAllowCellularNever = 0,
  AWNetworkAccessAllowCellularAlways = 1,
  AWNetworkAccessAllowCellularNotRoaming = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AWNetworkAccessAllowWiFi, "AllowWiFiNetworkAccess", closed) {
  AWNetworkAccessAllowWiFiAlways = 1,
  AWNetworkAccessAllowWiFiFilter = 2,
};

typedef SWIFT_ENUM(NSInteger, AWSDKCryptError, closed) {
  AWSDKCryptErrorStoreIsLocked = 0,
  AWSDKCryptErrorInvalidKey = 1,
  AWSDKCryptErrorInvalidOutputData = 2,
};

typedef SWIFT_ENUM(NSInteger, AWSDKEncryptedStoreError, closed) {
  AWSDKEncryptedStoreErrorStoreIsLocked = 0,
  AWSDKEncryptedStoreErrorStoreTypeNotSupported = 1,
  AWSDKEncryptedStoreErrorStoreMigrationFailed = 2,
  AWSDKEncryptedStoreErrorFileDoesNotExist = 3,
  AWSDKEncryptedStoreErrorInternalEncryptionError = 4,
  AWSDKEncryptedStoreErrorInternalError = 5,
};


SWIFT_CLASS("_TtC5AWSDK17AWSDKErrorDomains")
@interface AWSDKErrorDomains : NSObject
/// @brief Domain for intialCheckDone errors which cause the AWSDK to stop execution.
/// @description The AWSDK setup flow begins when the application starts for the first time or on
/// everytime the application comes into foregroud. The call to initialCheckDone occurs when it has finished its work with either
/// an error or nil if everything finished successfully.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull setup;)
+ (NSString * _Nonnull)setup SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull encryptedStore;)
+ (NSString * _Nonnull)encryptedStore SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull updateCredentials;)
+ (NSString * _Nonnull)updateCredentials SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull crypt;)
+ (NSString * _Nonnull)crypt SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull pendingCerificate;)
+ (NSString * _Nonnull)pendingCerificate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AWSDKPendingCertificateFetchError, closed) {
  AWSDKPendingCertificateFetchErrorCertificateIssuancePending = 0,
  AWSDKPendingCertificateFetchErrorRetryIntervalNotReached = 1,
  AWSDKPendingCertificateFetchErrorMaximumAllowedAttemptsEllapsed = 2,
  AWSDKPendingCertificateFetchErrorMissingPendingCertificateFetchRequest = 3,
  AWSDKPendingCertificateFetchErrorFailedToSavePendingCertificateRequestSecurely = 4,
  AWSDKPendingCertificateFetchErrorFailedToIdentifyIssuerForPendingCertificateRequest = 5,
};

typedef SWIFT_ENUM(NSInteger, AWSDKSetupError, closed) {
  AWSDKSetupErrorInternalError = 0,
  AWSDKSetupErrorStopSDKRequested = 1,
  AWSDKSetupErrorRegisteringApplicationBlocked = 2,
  AWSDKSetupErrorEnrollmentInformationSetup = 3,
  AWSDKSetupErrorEmptyProfiles = 4,
  AWSDKSetupErrorProxyFailedToStart = 5,
  AWSDKSetupErrorIntegratedAuthenticationCertificatesNotDownloaded = 6,
  AWSDKSetupErrorApplicationIdentityNotSet = 7,
  AWSDKSetupErrorFailedToFetchPinningCertificate = 8,
  AWSDKSetupErrorFailedToFetchEnvironmentInformationFromAnchor = 9,
  AWSDKSetupErrorCallBackSchemeNotConfigured = 10,
  AWSDKSetupErrorAirWatchApplicationSchemeNotWhitelisted = 11,
  AWSDKSetupErrorAnchorRequiredForThirdPartyApplictionBootstrap = 12,
  AWSDKSetupErrorFailedToReportUnenrollmentStatus = 13,
  AWSDKSetupErrorUserReachedMaximumAllowedUnlockAttempts = 14,
  AWSDKSetupErrorDeviceIsCompromised = 15,
  AWSDKSetupErrorConsoleVersionNotCompatible = 16,
  AWSDKSetupErrorInvalidKeyWrappingConfiguration = 17,
  AWSDKSetupErrorProtectedDataIsUnavailable = 18,
};

typedef SWIFT_ENUM(NSInteger, AWSDKUpdateCredentialsError, closed) {
  AWSDKUpdateCredentialsErrorAuthenticationFailed = 0,
  AWSDKUpdateCredentialsErrorUserCancelled = 1,
};


SWIFT_CLASS("_TtC5AWSDK16AnalyticsHandler")
@interface AnalyticsHandler : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsHandler * _Nonnull sharedInstance;)
+ (AnalyticsHandler * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL enabled;
- (void)recordEvent:(enum AWAnalyticsEvent)event eventName:(NSString * _Nonnull)eventName eventValue:(NSString * _Nonnull)eventValue valueType:(enum AWAnalyticsEventValueType)valueType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// @brief		Analytics payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the analtyics group of an SDK profile.
/// @version     6.0
SWIFT_CLASS_NAMED("AnalyticsPayload")
@interface AWAnalyticsPayload : AWProfilePayload
@property (nonatomic, readonly) BOOL enabled;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


/// @brief		Authentication payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the authentication group of an SDK profile.
/// @version     6.0
SWIFT_CLASS_NAMED("AuthenticationPayload")
@interface AWAuthenticationPayload : AWProfilePayload
@property (nonatomic, readonly) enum AWAuthenticationMethod authenticationMethod;
/// The minimum length of a passcode.
/// <em>This only applies to passcodes</em>
@property (nonatomic, readonly) NSInteger minimumPasscodeLength;
/// The minimum complex characters a passcode must contain.
/// <em>This only applies to passcodes.</em>
@property (nonatomic, readonly) NSInteger minimumComplexCharacters;
/// The maximum amount of days before a passcode expires and a new one must be set.
/// A Value <= 0 is interpreted as no maximum passcode age
@property (nonatomic, readonly) NSInteger maximumPasscodeAge;
/// The amount of passcodes that must be unique before reusing one is allowed.
/// <em>This only applies to passcodes.</em>
@property (nonatomic, readonly) NSInteger passcodeHistory;
/// The amount of passcodes that must be unique before reusing one is allowed.
/// <em>This only applies to passcodes.</em>
@property (nonatomic, readonly) NSInteger minimumUniquePasscodesBeforeReuse;
/// Amount of time the application can be unlocked without prompting for the passcode.
/// <em>This applies to username / password & passcodes</em>
@property (nonatomic, readonly) NSTimeInterval gracePeriod;
/// Number of failed authentication attempts allowed before actions should be executed.
/// <em>This applies to username / password & passcode.</em>
@property (nonatomic, readonly) NSInteger maximumFailedAttempts;
/// The idle time (in minute) before application will auto lock
@property (nonatomic, readonly) NSInteger autoLockMinute;
/// Determine if device passcode level should be required.
/// <em>This start being implemented in 6.4 to replace authenticationMethod = 1 (passcode)</em>
@property (nonatomic, readonly) BOOL requirePasscode;
/// A boolean indicating if Single Sign-On is enabled.
@property (nonatomic, readonly) BOOL enableSingleSignOn;
@property (nonatomic, readonly) enum AWPasscodeMode passcodeMode;
/// A boolean indicating if simple passcodes are allowed to be used.
@property (nonatomic, readonly) BOOL allowSimple;
/// Amount of time the application can be unlocked without prompting for the passcode.
@property (nonatomic, readonly) NSInteger passcodeTimeout;
@property (nonatomic, readonly, copy) NSString * _Nullable policyId;
@property (nonatomic, readonly) BOOL isV2;
/// A boolean indicating if Integrated Authentication is enabled.
@property (nonatomic, readonly) BOOL enableIntegratedAuthentication;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allowedSites;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull payloadDictionary;
@property (nonatomic, readonly) enum AWBiometricMethod biometricMethod;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


/// @brief		Branding payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the branding group of an SDK profile.
/// @version     5.8
SWIFT_CLASS_NAMED("BrandingPayload")
@interface AWBrandingPayload : AWProfilePayload
/// A boolean indicating if Branding is enabled.
@property (nonatomic, readonly) BOOL enableBranding;
@property (nonatomic, readonly) BOOL customBranding;
/// The Organization Name.
@property (nonatomic, readonly, copy) NSString * _Nullable organizationName;
/// The primary highlight color.
@property (nonatomic, readonly, strong) UIColor * _Nullable primaryHighlightColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable primaryColor;
/// The secondary highlight color.
@property (nonatomic, readonly, strong) UIColor * _Nullable secondaryHighlightColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable secondaryColor;
/// The navigation bar and toolbar color.
@property (nonatomic, readonly, strong) UIColor * _Nullable toolbarColor;
/// The primary text color.
@property (nonatomic, readonly, strong) UIColor * _Nullable primaryTextColor;
/// The secondary text color.
@property (nonatomic, readonly, strong) UIColor * _Nullable secondaryTextColor;
/// The login title text color.
@property (nonatomic, readonly, strong) UIColor * _Nullable loginTitleTextColor;
/// The tertiary text color.
@property (nonatomic, readonly, strong) UIColor * _Nullable tertiaryTextColor;
/// The toolbar text color.
@property (nonatomic, readonly, strong) UIColor * _Nullable toolbarTextColor;
/// The background image for non-retina iPhones & iPod touches.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPhoneBackgroundImageURL;
/// The background image for retina iPhones & iPod touches.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPhone2xBackgroundImageURL;
@property (nonatomic, readonly, copy) NSURL * _Nullable iPhone52xBackgroundImageURL;
/// The background image for non-retina iPads.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPadBackgroundImageURL;
/// The background image for retina iPads.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPad2xBackgroundImageURL;
/// The company image logo for non-retina iPhones & iPod touches.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPhoneCompanyLogoURL;
/// The company image logo for non-retina iPhones & iPod touches.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPhone2xCompanyLogoURL;
/// The company image logo for non-retina iPads.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPadCompanyLogoURL;
/// The company image logo for non-retina iPads.
@property (nonatomic, readonly, copy) NSURL * _Nullable iPad2xCompanyLogoURL;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC5AWSDK13BreezyPayload")
@interface BreezyPayload : AWProfilePayload
@property (nonatomic, readonly, copy) NSString * _Nullable breezyMDMAuthToken;
@property (nonatomic, readonly, copy) NSString * _Nullable breezyServerURL;
@property (nonatomic, readonly, copy) NSString * _Nullable breezyOauthConsumerID;
@property (nonatomic, readonly, copy) NSString * _Nullable breezyOauthConsumerSecret;
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end

@protocol AWConsoleCommand;
@protocol AWConsoleCommandResponse;

SWIFT_PROTOCOL("_TtP5AWSDK14CommandHandler_")
@protocol CommandHandler
- (id <AWConsoleCommandResponse> _Nullable)processWithCommand:(id <AWConsoleCommand> _Nonnull)command SWIFT_WARN_UNUSED_RESULT;
@end

@class NSArray;

/// @brief		Compliance payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the compliance group of an SDK profile.
/// @version     6.0
SWIFT_CLASS_NAMED("CompliancePayload")
@interface AWCompliancePayload : AWProfilePayload
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kComplianceStatusKey;)
+ (NSString * _Nonnull)kComplianceStatusKey SWIFT_WARN_UNUSED_RESULT;
/// A boolean indicating if compromised (jailbroken) devices should be prevented.
@property (nonatomic, readonly) BOOL preventCompromisedDevices;
/// A boolean indicating if device restorations should be prevented.
@property (nonatomic, readonly) BOOL preventRestoringBackupDevices;
/// An array of actions to be performed if the device is compromised.
@property (nonatomic, readonly, strong) NSArray * _Nonnull preventCompromisedDevicesActions;
/// A boolean indicating if compromised (jailbroken) devices should be prevented.
@property (nonatomic, readonly) BOOL enableCompromisedProtection;
/// A string for the id of the compromised policy.
@property (nonatomic, readonly, copy) NSString * _Nullable compromisedPolicyID;
/// For constructing this payload in Objective-C UT. It should not be called for elsewhere
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL_NAMED("ConsoleCommand")
@protocol AWConsoleCommand
@property (nonatomic, readonly, copy) NSString * _Nonnull UUID;
@property (nonatomic, readonly) enum AWCommandType type;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull commandInfo;
@end


SWIFT_PROTOCOL_NAMED("ConsoleCommandResponse")
@protocol AWConsoleCommandResponse
@property (nonatomic, readonly) enum AWCommandStatus status;
@property (nonatomic, readonly, copy) NSString * _Nonnull payloadIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull commandTarget;
@property (nonatomic, readonly, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable certificateResponse;
@property (nonatomic, readonly, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable installedProfilesResponse;
@end


SWIFT_PROTOCOL_NAMED("ConsoleSupportInformation")
@protocol AWConsoleSupportInformation
@property (nonatomic, readonly, copy) NSString * _Nullable email;
@property (nonatomic, readonly, copy) NSString * _Nullable telephoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable errorMessage;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, AWContentFilterType, "ContentFilterType", closed) {
  AWContentFilterTypeNone = 0,
  AWContentFilterTypeWebsense = 1,
};


SWIFT_CLASS_NAMED("ContentFilteringPayload")
@interface AWContentFilteringPayload : AWProfilePayload
@property (nonatomic, readonly) enum AWContentFilterType contentFilterType;
@property (nonatomic, readonly) NSInteger contentFilterProxyId;
@property (nonatomic, readonly, copy) NSString * _Nullable websensePacAddress;
@property (nonatomic, readonly) NSInteger websenseAccountId;
@property (nonatomic, readonly, copy) NSString * _Nullable websenseSecurityKey;
@property (nonatomic, readonly) NSInteger websenseProxyId;
/// For constructing this payload in UT. It should not be called for elsewhere
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL_NAMED("ControllerCommandManagementDelegate")
@protocol AWControllerCommandManagementDelegate
- (void)controllerDidStartLoadingCommands;
- (void)controllerDidFailToLoadCommandsWithError:(NSError * _Nonnull)error;
- (void)controllerDidFinishLoadingCommands;
@end


/// @brief     Custom payload that is contained within a ‘AWProfile’.
/// @version   6.0
SWIFT_CLASS_NAMED("CustomPayload")
@interface AWCustomPayload : AWProfilePayload
@property (nonatomic, readonly, copy) NSString * _Nullable settings;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("CustomerLogger")
@interface AWCustomerLogger : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AWCustomerLogger * _Nonnull sharedInstance;)
+ (AWCustomerLogger * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)logWithError:(NSString * _Nonnull)input function:(NSString * _Nonnull)function file:(NSString * _Nonnull)file line:(NSUInteger)line;
- (void)logWithWarning:(NSString * _Nonnull)input function:(NSString * _Nonnull)function file:(NSString * _Nonnull)file line:(NSUInteger)line;
- (void)logWithInfo:(NSString * _Nonnull)input function:(NSString * _Nonnull)function file:(NSString * _Nonnull)file line:(NSUInteger)line;
- (void)logWithVerbose:(NSString * _Nonnull)input function:(NSString * _Nonnull)function file:(NSString * _Nonnull)file line:(NSUInteger)line;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL_NAMED("DeviceInformation")
@protocol AWDeviceInformation
@property (nonatomic, readonly) enum AWEnrollmentStatus enrollmentStatus;
@property (nonatomic, readonly) enum AWComplianceStatus complianceStatus;
@property (nonatomic, readonly) BOOL isManaged;
@property (nonatomic, readonly) enum AWDeviceManagmentType managementType;
@property (nonatomic, readonly, copy) NSString * _Nonnull groupName;
@property (nonatomic, readonly, copy) NSString * _Nonnull groupID;
@property (nonatomic, readonly, copy) NSString * _Nonnull consoleVersion;
@end


SWIFT_CLASS("_TtC5AWSDK27DeviceInformationController")
@interface DeviceInformationController : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DeviceInformationController * _Nonnull sharedController;)
+ (DeviceInformationController * _Nonnull)sharedController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSString * _Nullable deviceServicesURL;
@property (nonatomic, readonly) enum AWSSOStatus ssoStatus;
+ (BOOL)isCurrentDeviceCompromised SWIFT_WARN_UNUSED_RESULT;
- (void)fetchDeviceInformationWithCompletion:(void (^ _Nonnull)(id <AWDeviceInformation> _Nullable, NSError * _Nullable))completion;
- (void)requestRequeryWithType:(enum AWRequeryType)type completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("EnrollmentAccount")
@interface AWEnrollmentAccount : NSObject
@property (nonatomic, readonly) NSInteger identifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull activationCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull username;
@property (nonatomic, readonly, copy) NSString * _Nonnull password;
@property (nonatomic, readonly, copy) NSString * _Nonnull authorizationToken;
@property (nonatomic, readonly) enum AWEnrollmentAuthenticationCredentials authenticationCredentialsType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithActivationCode:(NSString * _Nullable)activationCode username:(NSString * _Nullable)username password:(NSString * _Nullable)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithActivationCode:(NSString * _Nullable)activationCode authorizationToken:(NSString * _Nullable)authorizationToken OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) BOOL isAccountAuthenticated;
@end


SWIFT_CLASS_NAMED("EnrollmentAccountAuthenticator")
@interface AWEnrollmentAccountAuthenticator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)authenticateAccountWithEnrollmentAccount:(AWEnrollmentAccount * _Nonnull)enrollmentAccount completion:(void (^ _Nonnull)(BOOL, AWEnrollmentAccount * _Nonnull, NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("GeofenceArea")
@interface AWGeofenceArea : NSObject
@property (nonatomic, readonly) CLLocationCoordinate2D center;
@property (nonatomic, readonly) CLLocationDistance radius;
@property (nonatomic, readonly, copy) NSString * _Nullable uniqueID;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// @brief       Geofence payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the geofence group of an SDK profile.
/// @version     6.0
SWIFT_CLASS_NAMED("GeofencePayload")
@interface AWGeofencePayload : AWProfilePayload
/// A boolean indicating if geofencing should be enabled.
@property (nonatomic, readonly) BOOL isEnabled;
/// An array containing all geofence area values.
@property (nonatomic, readonly, copy) NSArray<AWGeofenceArea *> * _Nonnull geofenceAreas;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("NetworkAccessPayload")
@interface AWNetworkAccessPayload : AWProfilePayload
@property (nonatomic, readonly) BOOL enableNetworkAccess;
@property (nonatomic, readonly) enum AWNetworkAccessAllowCellular allowCellularConnection;
@property (nonatomic, readonly) enum AWNetworkAccessAllowWiFi allowWifiConnection;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allowedSSIDs;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


/// @brief       OfflineAccessPayload payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the Offline Access group of an SDK profile.
/// @version     6.0
SWIFT_CLASS_NAMED("OfflineAccessPayload")
@interface AWOfflineAccessPayload : AWProfilePayload
@property (nonatomic, readonly) BOOL enableOfflineAccess;
@property (nonatomic, readonly) NSTimeInterval maximumSecondsAllowedOffline;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end

@class AWRestrictionsPayload;
@class AWWebsiteFilteringPayload;

/// @brief		Represents an unmanaged configuration profile.
/// @details     Profile containing multiple payloads that are used to configure a device and application.
/// @version     6.0
SWIFT_CLASS_NAMED("Profile")
@interface AWProfile : NSObject
/// @name Generic Profile Information
@property (nonatomic, readonly, copy) NSString * _Nullable displayName;
@property (nonatomic, readonly, copy) NSString * _Nullable comments;
@property (nonatomic, readonly, copy) NSString * _Nullable identifier;
@property (nonatomic, readonly, copy) NSString * _Nullable organization;
@property (nonatomic, readonly, copy) NSString * _Nullable uuid;
@property (nonatomic, readonly) enum AWConfigurationProfileType profileType;
@property (nonatomic, readonly) BOOL isSDKProfile;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull dictionaryToStore;
/// @name SDK Profile Payloads
@property (nonatomic, readonly, strong) AWGeofencePayload * _Nullable geofencePayload;
@property (nonatomic, readonly, strong) AWAnalyticsPayload * _Nullable analyticsPayload;
@property (nonatomic, readonly, strong) AWRestrictionsPayload * _Nullable restrictionsPayload;
@property (nonatomic, readonly, strong) AWCompliancePayload * _Nullable compliancePayload;
@property (nonatomic, readonly, strong) AWAuthenticationPayload * _Nullable authenticationPayload;
@property (nonatomic, readonly, strong) AWBrandingPayload * _Nullable brandingPayload;
@property (nonatomic, readonly, strong) BreezyPayload * _Nullable breezyPayload;
@property (nonatomic, readonly, strong) AWCustomPayload * _Nullable customPayload;
@property (nonatomic, readonly, strong) AWOfflineAccessPayload * _Nullable offlineAccessPayload;
@property (nonatomic, readonly, strong) AWNetworkAccessPayload * _Nullable networkAccessPayload;
@property (nonatomic, readonly, strong) AWContentFilteringPayload * _Nullable contentFilteringPayload;
@property (nonatomic, readonly, strong) AWWebsiteFilteringPayload * _Nullable websiteFilteringPayload;
- (nonnull instancetype)initWithInfo:(NSDictionary<NSString *, id> * _Nonnull)info OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


@interface AWProfile (SWIFT_EXTENSION(AWSDK))
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
@end


@interface AWProfile (SWIFT_EXTENSION(AWSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


@interface AWProfile (SWIFT_EXTENSION(AWSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// @brief		Access control payload that is contained in an ‘AWProfile’.
/// @details     A profile payload that represents the access control group of an SDK profile.
/// @version     6.0
SWIFT_CLASS_NAMED("RestrictionsPayload")
@interface AWRestrictionsPayload : AWProfilePayload
/// A boolean indicating if Copy from the outside and Paste to inside is allowed *
@property (nonatomic, readonly) BOOL enableCopyAndPasteInTo;
/// The reverse value of enableCopyAndPasteInTo *
@property (nonatomic, readonly) BOOL preventCopyAndPasteInTo;
/// A boolean indicating if Copy from the inside and Paste to outside is allowed *
@property (nonatomic, readonly) BOOL enableCopyAndPasteOut;
/// The reverse value of enableCopyAndPasteOut *
@property (nonatomic, readonly) BOOL preventCopyPaste;
/// A boolean indicating whether to only allow open document in allowed list of app
@property (nonatomic, readonly) BOOL restrictDocumentToApps;
/// A list of Apps that’re allowed to open documents
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allowedApplications;
/// A boolean indicating if printing is allowed.
@property (nonatomic, readonly) BOOL printingEnabled;
/// A boolean indicating if data loss prevention is enabled.
@property (nonatomic, readonly) BOOL enableDataLossPrevention;
/// A boolean indicating if watermark should be displayed on content that has watermark.
@property (nonatomic, readonly) BOOL enableWatermark;
/// The string that indicate the watermark overlay on the content.
@property (nonatomic, readonly, copy) NSString * _Nullable watermarkOverlay;
/// A boolean indicating if third party keyboards are blocked. Not blocked by default
@property (nonatomic, readonly) BOOL preventCustomKeyboards;
@property (nonatomic, readonly) BOOL enableMailComposing;
@property (nonatomic, readonly) BOOL enableLocationReporting;
@property (nonatomic, readonly) BOOL enableDataBackup;
@property (nonatomic, readonly) BOOL enableCameraAccess;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("SDKBeaconTransmitter")
@interface AWSDKBeaconTransmitter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AWSDKBeaconTransmitter * _Nonnull sharedTransmitter;)
+ (AWSDKBeaconTransmitter * _Nonnull)sharedTransmitter SWIFT_WARN_UNUSED_RESULT;
- (void)sendBeaconWithUpdatedAPNSToken:(NSString * _Nonnull)updatedAPNSToken completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
- (void)startSendingDeviceStatusBeaconWithTransmitFrequency:(NSTimeInterval)transmitFrequency onInitialBeaconSendCompletion:(void (^ _Nullable)(BOOL, NSError * _Nullable))onInitialBeaconSendCompletion;
- (void)stopSendingDeviceStatusBeacon;
- (void)sendDeviceStatusBeaconWithCompletion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
- (NSDate * _Nullable)lastSuccessfulBeaconTimeStamp SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SSLPinningInterface")
@interface AWSSLPinningInterface : NSObject
+ (NSArray<NSString *> * _Nullable)getStoredPublicKeysForPinningForHost:(NSString * _Nonnull)host SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5AWSDK28SupportInformationController")
@interface SupportInformationController : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SupportInformationController * _Nonnull sharedInstance;)
+ (SupportInformationController * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
/// Retrieve the support information for email and telephone that’s configured on console
/// @return AWError.SDK.General.moduleNotInitialized If calling this API directly without initializing the
/// SDK and not reaching the delegate call for initial check done then an error will occur
/// @return AWError.SDK.CoreNetwork.CTL.createRequestFailure(error.localizedDescription) - network related failure
/// @return AWError.SDK.General.jsonDeserializationFailed - could not unwrap the response data which is supposed to be JSON
/// @return AWError.SDK.General.configurationValuesUnavailable.error - An Error was returned on the server. Check the error message for a possible message
/// @return SupportInformation If an object is returned, check that there is no error message and use the data accordingly.
- (void)retrieveSupportInfoWithCompletion:(void (^ _Nonnull)(id <AWConsoleSupportInformation> _Nullable, NSError * _Nullable))completion;
@end


SWIFT_CLASS_NAMED("UserInformation")
@interface AWUserInformation : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userName;
@property (nonatomic, readonly, copy) NSString * _Nonnull userIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull firstName;
@property (nonatomic, readonly, copy) NSString * _Nonnull lastName;
@property (nonatomic, readonly, copy) NSString * _Nonnull email;
@property (nonatomic, readonly, copy) NSString * _Nonnull domain;
@property (nonatomic, readonly, copy) NSString * _Nonnull groupID;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5AWSDK25UserInformationController")
@interface UserInformationController : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UserInformationController * _Nonnull sharedInstance;)
+ (UserInformationController * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
/// @brief Retrieve the user information.
/// @return If calling this API directly without initializing the SDK and not reaching the delegate call for initial check done then an error will occur
- (void)retrieveUserInfoWithCompletionHandler:(void (^ _Nonnull)(AWUserInformation * _Nullable, NSError * _Nullable))completionHandler;
@end


SWIFT_CLASS_NAMED("WebsiteFilteringPayload")
@interface AWWebsiteFilteringPayload : AWProfilePayload
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull websiteFilterCategories;
@property (nonatomic, readonly) NSInteger websiteFilterId;
@property (nonatomic, readonly) enum AWWebsiteFilterType filterType;
/// For constructing this payload in UT. It should not be called for elsewhere
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)payloadType SWIFT_WARN_UNUSED_RESULT;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
